name: tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.x, 3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v2
      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install poetry
        run: pip install poetry

      - name: install dev dependencies
        run: poetry install --only dev

      - name: run tests
        run: poetry run python -m pytest -vvs
